In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('src_data/insurance.csv')

In [3]:
print(df.shape)
df.head(5)

(1338, 7)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### Preprocessing

### label encoding 
- sex, smoker, region

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le_sex = LabelEncoder()
le_region = LabelEncoder()
le_children = LabelEncoder()
le_smoker = LabelEncoder()

In [6]:
le_sex.fit(df['sex'])
le_region.fit(df['region'])
le_smoker.fit(df['smoker'])

LabelEncoder()

In [7]:
df['sex'] = le_sex.transform(df['sex'])
df['region'] = le_region.transform(df['region'])
df['smoker'] = le_smoker.transform(df['smoker'])

In [8]:
print(df.shape)
df.head(5)

(1338, 7)

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [9]:
# To see the mapping for each column:
print("\nSex Mapping:", dict(zip(le_sex.classes_, le_sex.transform(le_sex.classes_))))
print("Region Mapping:", dict(zip(le_region.classes_, le_region.transform(le_region.classes_))))
print("Smoker Mapping:", dict(zip(le_smoker.classes_, le_smoker.transform(le_smoker.classes_))))

Sex Mapping: {'female': np.int64(0), 'male': np.int64(1)}
Region Mapping: {'northeast': np.int64(0), 'northwest': np.int64(1), 'southeast': np.int64(2), 'southwest': np.int64(3)}
Smoker Mapping: {'no': np.int64(0), 'yes': np.int64(1)}

### Standard scaling

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(df[['bmi']])

StandardScaler()

In [13]:
df['bmi'] = scaler.transform(df[['bmi']])
print(df.shape)
print(df.head(3))

(1338, 7)
   age  sex       bmi  children  smoker  region     charges
0   19    0 -0.453320         0       1       3  16884.9240
1   18    1  0.509621         1       0       2   1725.5523
2   28    1  0.383307         3       0       2   4449.4620

## Preperation

#### Train_Test_Split

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
train, test = train_test_split(df, test_size=0.2, random_state=42)

In [16]:
X, Y = train.iloc[:, :-1], train['charges']
x, y = test.iloc[:, :-1], test['charges']

In [17]:
[x.shape for x in [X, Y, x, y]]

[(1070, 6), (1070,), (268, 6), (268,)]

### Model Training

In [18]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [19]:
dt = DecisionTreeRegressor()
rf = RandomForestRegressor()

In [20]:
dt.fit(X, Y)
rf.fit(X, Y)

RandomForestRegressor()

## Model Evaluation

In [21]:
from sklearn.metrics import mean_absolute_error

In [22]:
{f'{model} with its MAE' : mean_absolute_error(y,model.predict(x)) for model in [dt, rf,]}

{'DecisionTreeRegressor() with its MAE': 2935.1254959291045,
 'RandomForestRegressor() with its MAE': 2481.036404329727}